$('#submit').click(()=>{
    var HospitalDetails={
        Hos_id:document.getElementById('exampleInputEmail1').value,
        Hos_name:document.getElementById('Hosname').value,
        Hos_loc:document.getElementById('Hosloc').value 
    }
    console.log(HospitalDetails)
    $.post('/FillHospitalsDetails',HospitalDetails,(data,status)=>{
         if(status == "success")
         {
            window.location.replace('/HospitalPage')
         }
    })
})
$('#home').click(()=>{
 console.log(1)
    window.location.replace('/AdminPage')
})
if(sessionStorage.getItem("key")==null)
{
    window.location.replace('/')
}
$("#logout").click(()=>{
    if(sessionStorage.getItem("key"))
    {
        sessionStorage.removeItem("key")
        window.location.replace('/')
    }
})